apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: trace
  namespace: {{ .Values.namespace }}
spec:
  mode: deployment
  serviceAccount: otel-collector
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      awsxray:
        endpoint: 0.0.0.0:2000
        transport: udp
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
      resourcedetection:
        detectors: [eks]
    exporters:
      awsxray:
        region: {{ .Values.region }}
    service:
      pipelines:
        traces:
          receivers: [otlp, awsxray]
          processors: [memory_limiter, batch, resourcedetection]
          exporters: [awsxray]