# Default values for agentic-rag.
# This is a YAML-formatted file.

# Specify the namespace where this service will be deployed
# Leave empty to use the namespace specified in the helm command
namespace: "default"

# Replica count for scaling
replicaCount: 1

image:
  repository: "agentic-platform-agentic-rag"
  tag: latest
  pullPolicy: Always

nameOverride: "agentic-rag"
fullnameOverride: "agentic-rag"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: PYTHONPATH
    value: /app

# Resource allocation
resources:
  requests:
    cpu: 100m      # 0.1 CPU core (10% of a core)
    memory: 256Mi  # 256 megabytes
  limits:
    memory: 512Mi  # 512 megabytes

# Ingress configuration
ingress:
  enabled: true
  path: "/agentic-rag"

# Service account for permissions
serviceAccount:
  name: "agentic-rag-agent-sa"
  create: true
  irsaConfigKey: "AGENT_ROLE_ARN"

# IRSA role configuration
irsaConfigKey: "AGENT_ROLE_ARN"

# Agent secret configuration
agentSecret:
  configKey: "AGENT_LITELLM_SECRET_ARN"

# Default values if keys aren't found in central config
configDefaults:
  LITELLM_API_ENDPOINT: "http://litellm.default.svc.cluster.local:80"
  RETRIEVAL_GATEWAY_ENDPOINT: "http://retrieval-gateway.default.svc.cluster.local:80/api/retrieval-gateway"
  MEMORY_GATEWAY_ENDPOINT: "http://memory-gateway.default.svc.cluster.local:80/api/memory-gateway"
