{{- $configMap := (lookup "v1" "ConfigMap" .Values.namespace "agentic-platform-config") -}}
{{- if $configMap -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "litellm.fullname" . }}-secret
  namespace: {{ include "litellm.namespace" . }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ include "litellm.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: litellm-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $configMap.data.LITELLM_CONFIG_SECRET_ARN }}
        conversionStrategy: Default
        decodingStrategy: None
{{- end }}
