apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "litellm.fullname" . }}-secret
  namespace: {{ include "litellm.namespace" . }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ include "litellm.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: litellm-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.aws.stackPrefix }}-litellm-secret
        conversionStrategy: Default
        decodingStrategy: None
