{{- $configMap := (lookup "v1" "ConfigMap" .Values.namespace "agentic-platform-config") -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "litellm.fullname" . }}-secretstore
  namespace: {{ include "litellm.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      {{- if $configMap }}
      region: {{ $configMap.data.AWS_DEFAULT_REGION }}
      {{- else }}
      region: us-east-1
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
