{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "litellm.namespace" . }}
  labels:
    app: {{ include "litellm.name" . }}
  {{- if include "litellm.irsaRoleArn" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "litellm.irsaRoleArn" . }}
  {{- end }}
{{- end }}
