apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
  namespace: {{ include "app.namespace" . }}
  labels:
    app: {{ include "app.name" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}