apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "app.name" . }}-secretstore
  namespace: {{ include "app.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ (lookup "v1" "ConfigMap" .Values.namespace "agentic-platform-config").data.AWS_DEFAULT_REGION }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
