apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "app.name" . }}-secretstore
  namespace: {{ include "app.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
