{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.serviceAccount.irsaRoleName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "app.irsaRoleArn" . }}
  {{- end }}
{{- end }}
