# Configuration for generate_summaries.py

# Amazon Bedrock configuration
model:
  id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  name: "Claude 3.7 Sonnet"
  provider: "Anthropic"

# Inference configuration
inference_config:
  temperature: 0.2
  max_tokens: 30000  # Increased from 15000 to 30000 to allow for much more detailed responses

# List of folders to analyze
folders_to_analyze:
  - "labs/module1"
  - "labs/module2"
  - "labs/module3"
  - "labs/module4"
  - "labs/module5"
  - "k8s"
  - "infrastructure"
  - "deploy"
 
# Output configuration
output:
  directory: "my-analysis"
  file_prefix: "SUMMARY-"

# Debug configuration
debug:
  enabled: true  # Set to true to enable debug output
  print_prompt: true  # Print the full prompt sent to the model

# File selection configuration
file_selection:
  max_notebooks: 1000       # Set to very high value to consume entire files
  max_notebook_cells: 10000 # Set to very high value to consume entire files
  max_python_files: 1000    # Set to very high value to consume entire files
  max_python_lines: 100000  # Set to very high value to consume entire files
  max_markdown_files: 1000  # Set to very high value to consume entire files
  max_yaml_files: 1000      # Set to very high value to consume entire files
  max_yaml_lines: 100000    # Set to very high value to consume entire files
  max_terraform_files: 1000 # Set to very high value to consume entire files
  max_terraform_lines: 100000 # Set to very high value to consume entire files
  max_shell_files: 1000     # Set to very high value to consume entire files
  max_shell_lines: 100000   # Set to very high value to consume entire files
  max_text_files: 1000      # Set to very high value to consume entire files
  max_text_lines: 100000    # Set to very high value to consume entire files
  include_patterns:         # Always include files matching these patterns
    - "main.py"
    - "*config*.py"
    - "*config*.yml"
    - "*config*.yaml"
    - "README*"
    - "utils.py"
    - "*agent*.py"
    - "*model*.py"
    - "*data*.py"
    - "*util*.py"
    - "*helper*.py"
    - "*service*.py"
    - "*client*.py"
    - "*api*.py"
    - "requirements.txt"
    - "Chart.yaml"
    - "values.yaml"
    - "deployment.yaml"
    - "service.yaml"
    - "ingress.yaml"
    - "*.tf"              # Include all Terraform files
    - "*.sh"              # Include all shell scripts
    - "*.txt"             # Include all text files
  exclude_patterns:         # Skip files/directories matching these patterns
    - "__pycache__"
    - "*.pyc"
    - "venv/*"
    - "*.log"
    - "*.tmp"
    - "*.png"
    - "*.jpg"
    - "*.JPG"
    - "*.jpeg"
    - "*.JPEG"
    - "*.gif"
    - "*.ico"
    - "*.svg"
    - "node_modules/*"
    - ".git/*"
