{{- $fullPath := printf "%s/%s" .Values.parameterStore.basePath .Values.environment }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentic-platform-config
  namespace: {{ .Values.parameterStore.namespace }}
  labels:
    app.kubernetes.io/managed-by: external-secrets-operator
    app.kubernetes.io/part-of: agentic-platform
    app.kubernetes.io/component: config
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ .Values.parameterStore.name }}
    kind: ClusterSecretStore
  target:
    name: agentic-platform-config
    creationPolicy: Owner
    template:
      type: ConfigMap
      metadata:
        labels:
          app: agentic-platform
  dataFrom:
  - extract:
      key: {{ $fullPath }}
