---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.parameterStore.name }}
  labels:
    app.kubernetes.io/managed-by: external-secrets-operator
    app.kubernetes.io/part-of: agentic-platform
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system
